#!/usr/bin/env python3
"""
Merge multiple .bib files into one, deduplicating by citation key.
When duplicates exist, keeps the entry with more content (more fields/longer).
"""

import re
import os
from pathlib import Path
from collections import defaultdict

def parse_bib_entries(content):
    """Parse .bib content into dict of {key: full_entry_text}"""
    entries = {}

    # Match @type{key, ... } allowing nested braces
    # This regex finds the start of each entry
    entry_pattern = re.compile(r'@(\w+)\s*\{\s*([^,\s]+)\s*,', re.IGNORECASE)

    positions = [(m.start(), m.group(1), m.group(2)) for m in entry_pattern.finditer(content)]

    for i, (start, entry_type, key) in enumerate(positions):
        # Find the end of this entry by counting braces
        brace_count = 0
        end = start
        started = False
        for j, char in enumerate(content[start:], start):
            if char == '{':
                brace_count += 1
                started = True
            elif char == '}':
                brace_count -= 1
            if started and brace_count == 0:
                end = j + 1
                break

        entry_text = content[start:end].strip()
        key_lower = key.lower()

        # If we already have this key, keep the longer/more complete entry
        if key_lower in entries:
            existing = entries[key_lower]
            # Prefer entry with more fields (proxy: more lines or more characters)
            if entry_text.count('\n') > existing['text'].count('\n') or \
               (entry_text.count('\n') == existing['text'].count('\n') and len(entry_text) > len(existing['text'])):
                entries[key_lower] = {'key': key, 'type': entry_type, 'text': entry_text, 'source': entries[key_lower]['source']}
        else:
            entries[key_lower] = {'key': key, 'type': entry_type, 'text': entry_text, 'source': ''}

    return entries

def merge_bib_files(file_paths, output_path):
    """Merge multiple .bib files into one."""
    all_entries = {}
    source_counts = defaultdict(int)

    for fpath in file_paths:
        if not os.path.exists(fpath):
            print(f"  Skipping (not found): {fpath}")
            continue

        try:
            with open(fpath, 'r', encoding='utf-8', errors='replace') as f:
                content = f.read()
        except Exception as e:
            print(f"  Error reading {fpath}: {e}")
            continue

        entries = parse_bib_entries(content)
        source_name = Path(fpath).parent.name

        new_count = 0
        updated_count = 0
        for key_lower, entry in entries.items():
            entry['source'] = source_name
            if key_lower not in all_entries:
                all_entries[key_lower] = entry
                new_count += 1
            else:
                # Check if new entry is more complete
                existing = all_entries[key_lower]
                if entry['text'].count('\n') > existing['text'].count('\n') or \
                   (entry['text'].count('\n') == existing['text'].count('\n') and len(entry['text']) > len(existing['text'])):
                    all_entries[key_lower] = entry
                    updated_count += 1

        print(f"  {source_name}: {len(entries)} entries ({new_count} new, {updated_count} updated)")
        source_counts[source_name] = len(entries)

    # Sort entries by key for consistent output
    sorted_entries = sorted(all_entries.values(), key=lambda e: e['key'].lower())

    # Write consolidated file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(f"% Consolidated references.bib\n")
        f.write(f"% Generated by merge_bib.py\n")
        f.write(f"% Total entries: {len(sorted_entries)}\n")
        f.write(f"% Source files: {len(source_counts)}\n\n")

        for entry in sorted_entries:
            f.write(entry['text'])
            f.write('\n\n')

    return len(sorted_entries), source_counts

if __name__ == '__main__':
    # DEPRECATED. Superseded by push_bib.py, which matches on DOI and normalized
    # title before falling back to the citation key, refuses on any match rather
    # than silently keeping the longer entry, and will not write while the central
    # bib is dirty. Use `push_bib.py` (or the /push-bib skill) instead.
    #
    # The project list below also predates the 2026-06/07 folder reorganizations,
    # so every path in it is stale. Kept for reference, not repaired: rebuild the
    # list from papers/INDEX.md if this is ever revived.
    base = Path(__file__).resolve().parents[1]

    # All project .bib files (excluding templates, archives, external libs)
    bib_files = [
        base / 'papers/HPC book/references.bib',  # Start with largest
        base / 'papers/Grammaticality_as_Kind_Miller/refs.bib',
        base / 'papers/Grammaticality_de_idealized/refs.bib',
        base / 'papers/echolocation/refs.bib',
        base / 'papers/Grammar_and_emergence/refs.bib',
        base / 'papers/English_kinship_terms/references.bib',
        base / 'papers/Independent_relative_whose/refs.bib',
        base / 'papers/countability/references.bib',
        base / 'papers/Definiteness_and_deitality/refs.bib',
        base / 'papers/Functions_as_Comparanda__Categories_as_Kinds__A_Homeostatic_Approach_to_Typology/references.bib',
        base / 'papers/Labels_to_Stabilisers/references.bib',
        base / 'papers/Language_as_a_Stack_of_Homeostatic_Property_Cluster_HPC_Kinds/refs.bib',
        base / 'papers/How_to_Study_Boundary_Phenomena_English_Reciprocals_and_the_Limits_of_Categorization/refs.bib',
        base / 'papers/Alternations-Bayesian/references.bib',
        base / 'papers/linguistics-metrology/references.bib',
        base / 'papers/linguistics-mereology/refs.bib',
        base / 'papers/Focus_modifiers_interrogative_heads/references.bib',
        base / 'papers/Transparent_free_relatives/refs.bib',
        base / 'papers/grammatical-variation-metastudy/refs.bib',
        base / 'papers/Constructions_as_causal_mesoscales_in_CE_2_0/refs.bib',
        base / 'papers/English_LBC_functionalist/11_bibliography.bib',
        base / 'papers/CxG_chunking_feature_selection/literature/bib.bib',
        base / 'personal/dillard-kimmerer/references.bib',
    ]

    output = base / '.house-style/references.bib'

    print("Merging .bib files...")
    total, counts = merge_bib_files(bib_files, output)
    print(f"\nConsolidated: {total} unique entries")
    print(f"Written to: {output}")
