#!/usr/bin/env python3
"""Extract <!-- claude-rule: NAME --> blocks from style-guide.md and write
.claude/rules/NAME.md files. Each output file starts with a do-not-edit
header.

Rule names handled by this generator (the *style* family):
  writing-style, latex-house-style, quarto-house-style, cgel-conventions

Non-style rules in .claude/rules/ (source-grounding, bibliography-workflow,
multi-model-dispatch, package-verification, agent-output-management,
decisions-log) are hand-authored canonical files. This script never touches
them.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
GUIDE = ROOT / ".house-style" / "style-guide.md"
OUT_DIR = ROOT / ".claude" / "rules"

GENERATED_RULES = (
    "writing-style",
    "latex-house-style",
    "quarto-house-style",
    "cgel-conventions",
)

HEADER = """<!--
GENERATED FILE. DO NOT EDIT.

Source: .house-style/style-guide.md
Generated by: .house-style/scripts/generate-claude-rules.py

To change this rule, edit the matching <!-- claude-rule: {name} --> block
in style-guide.md and run: make claude-rules
-->

"""


def extract_blocks(guide_text: str, rule_name: str) -> list[str]:
    pattern = re.compile(
        r"<!--\s*claude-rule:\s*" + re.escape(rule_name) + r"\s*-->\n(.*?)\n<!--\s*/claude-rule\s*-->",
        re.DOTALL,
    )
    return [m.strip() for m in pattern.findall(guide_text)]


def render(rule_name: str, blocks: list[str]) -> str:
    body = "\n\n".join(blocks)
    return HEADER.replace("{name}", rule_name) + body + "\n"


def main() -> int:
    if not GUIDE.exists():
        print(f"ERROR: source not found: {GUIDE}", file=sys.stderr)
        return 1
    guide_text = GUIDE.read_text()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    wrote, skipped = 0, 0
    for name in GENERATED_RULES:
        blocks = extract_blocks(guide_text, name)
        out_path = OUT_DIR / f"{name}.md"
        if not blocks:
            print(f"  (no blocks for '{name}' — skipping)", file=sys.stderr)
            skipped += 1
            continue
        out_path.write_text(render(name, blocks))
        print(f"  wrote {out_path.relative_to(ROOT)}  ({len(blocks)} block(s), {len(out_path.read_text().splitlines())} lines)", file=sys.stderr)
        wrote += 1

    print(f"done: {wrote} written, {skipped} skipped", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
